README.md, resource_sentry_organization.go, resource_sentry_project.go, resource_sentry_team.go
Adds support for [terraform import](https://www.terraform.io/docs/import/index.html)
Fixes https://github.com/jianyuan/terraform-provider-sentry/issues/1
=> Allow importing existing resources

client.go, provider.go, resource_sentry_key.go
Resource to manage client keys using:
https://docs.getsentry.com/hosted/api/projects/post-project-keys/
=> Sentry Key resource

client.go, resource_sentry_project.go
It allows to automatically resolve an issue if it hasn't been seen for this amount of time.
=> Allow configuring the auto resolve setting

client.go, resource_sentry_key.go
Update the name of a key using:
https://docs.sentry.io/api/projects/put-project-key-details/
=> Update key names, instead of recreating them

example/sentry.tf, sentry/data_source_sentry_key.go, sentry/data_source_sentry_key_test.go, sentry/provider.go
New data source: sentry_key. The parameters are the same as the sentry_key resource.
Documentation will be coming soon when I apply the official template to this project.
Closes #14.
=> Implement data source: sentry_key

README.md
=> Link to sentry website

go.mod, go.sum, sentry/data_source_sentry_organization.go, sentry/data_source_sentry_organization_test.go, sentry/provider.go
New data source: Sentry organization
=> Data source: Sentry organization

sentry/import_sentry_team.go
The copy-pasta was just a little too saucy.
=> Fix wrong wording in error msg on import team

README.md, sentry/resource_sentry_project.go
Signed-off-by: Cédric Menassa <cedric.menassa@gmail.com>
=> Add resolve_age as optional project parameter

sentry/resource_sentry_project_rule.go
This fixes the issue with rule reads not being written to state.
=> Fix importin rule resources

docs/index.md, sentry/provider.go
=> Sync documentation with code

docs/resources/organization_member.md, examples/resources/sentry_organization_member/resource.tf
=> fix: sentry_organization_member was missing the required organization fied

sentry/resource_sentry_issue_alert.go
Resolves https://github.com/jianyuan/terraform-provider-sentry/issues/259
=> bugfix: validate name length in sentry_issue_alert resource

sentry/resource_sentry_project.go
=> Add special case for "other" platform

sentry/resource_sentry_project.go, sentry/resource_sentry_team_test.go
=> Fix platform validation

docs/data-sources/key.md, go.mod, go.sum, sentry/data_source_sentry_key.go
This is a potential fix for the issue described [here](https://github.com/jianyuan/terraform-provider-sentry/issues/233#issuecomment-1346580905).
=> Change project_id type to string in key resource

docs/resources/key.md, examples/resources/sentry_key/import.sh
=> fix: sentry_key resource import statement

docs/resources/issue_alert.md
I have not verified that all examples work but only went through them visually (and only in this file).
=> fix: json syntax error in issue alert example

docs/resources/notification_action.md, internal/provider/resource_notification_action.go
Related: https://github.com/jianyuan/terraform-provider-sentry/pull/408
=> fix: update spike-protection in sentry_notification_action

.github/workflows/test.yml
Run tests against Terraform 1.7.*
=> feat: test against terraform `1.7.*`

docs/resources/key.md, sentry/resource_sentry_key.go
See https://github.com/jianyuan/terraform-provider-sentry/issues/233
=> fix: Extend the Project ID range by changing the type from int to string

docs/index.md, examples/provider/provider.tf, internal/provider/provider.go, sentry/provider.go, templates/index.md.tmpl
=> ref: update provider description

docs/data-sources/all_keys.md, docs/data-sources/key.md, docs/resources/key.md, internal/provider/data_source_all_client_keys.go, internal/provider/data_source_client_key.go, internal/provider/resource_client_key.go
Resolves https://github.com/jianyuan/terraform-provider-sentry/issues/460
=> docs: Add units to rate limit description

sentry/resource_sentry_metric_alert.go
this PR will fix https://github.com/jianyuan/terraform-provider-sentry/issues/485
=> owner and environment of sentry_metric_alert should not computed value

docs/data-sources/all_keys.md, docs/data-sources/all_organization_members.md, docs/data-sources/all_projects.md, docs/data-sources/issue_alert.md, docs/data-sources/key.md, docs/data-sources/organization.md, docs/data-sources/organization_integration.md, docs/data-sources/organization_member.md, docs/data-sources/project.md, internal/provider/data_source_all_client_keys.go, internal/provider/data_source_all_organization_members.go, internal/provider/data_source_all_projects.go, internal/provider/data_source_client_key.go, internal/provider/data_source_issue_alert.go, internal/provider/data_source_organization.go, internal/provider/data_source_organization_integration.go, internal/provider/data_source_organization_member.go, internal/provider/data_source_project.go, internal/provider/utils.go
=> ref: Refactor data sources
