jianyuan/terraform-provider-sentry

resource_sentry_project.go

Previously the resolve age was never send when updating the project
resurce causing plan to always display changes to apply.

Fixes project resolve age updating

---

README.md
client.go
provider.go
resource_sentry_plugin.go

The API isn't officially documented yet, but you can see the implementation
here: https://github.com/getsentry/sentry/blob/80786ee407b4abf3b7b7f35986976de687f1134e/src/sentry/api/endpoints/project_plugin_details.py
I tested the resource against the hosted sentry.

Resource to manage sentry plugins

---

resource_sentry_key.go

Without this, the key would always be recreated when using a list
of projects like and adding a new project.
```
resource "sentry_project" "project" {
count        = "${length(var.apps)}"
organization = "${sentry_organization.contentful.id}"
team         = "${sentry_team.default.id}"
name         = "${element(var.apps, count.index)}"
resolve_age  = "${var.sentry_resolve_age}"
}
resource "sentry_key" "key" {
count        = "${length(var.apps)}"
organization = "${sentry_organization.contentful.id}"
project      = "${element(sentry_project.project.*.id, count.index)}"
name         = "Node"
}
```

Remove ForceNew from Key project and organization

---

sentry/resource_sentry_project.go

Deprecate `is_bookmarked` parameter of a Project. Doesn't make sense in a multi-user scenario.
Closes #15.

Deprecate is_bookmarked

---

sentry/resource_sentry_key.go

@jianyuan if you'd be so kind 😄 If the project is not there anymore, the key is most certainly gone, too.

`sentry_key` resource should handle external project deletion

---

sentry/resource_sentry_project.go

When importing a Sentry project into my state file, I noticed that the help text incorrectly prompts to the user for the `team-slug` instead of the `project-slug`.

Clarifying import help text for projects

---

README.md

I recently used your terraform plugin and initially ran into trouble thinking that it did not support the client keys. I would like to update the readme to document the resource and data source for the client keys.

Added documentation for the sentry_key resource and data source

---

go.mod
go.sum

Since git.apache.org is down this PR replaces the module source to use the github mirror.
I got the fix from here: https://github.com/kubernetes/minikube/issues/5245

Replaces apache thrift module source

---

sentry/resource_sentry_key.go
sentry/resource_sentry_key_test.go

NOTE: This depends upon the following PR for `go-sentry` and a corresponding update to vendor files: https://github.com/jianyuan/go-sentry/pull/2
Lets users optionally supply rate limits when creating project keys:
```
resource "sentry_key" "test_key_rate_limit" {
organization = "widget-corp"
project = "hello-world"
name = "Test key"
rate_limit_window = 86400
rate_limit_count = 1000
}
```

Add project key rate limit

---

README.md

Terraform 0.12 warns if you use the old, verbose syntax.

Modernize README for Terraform 0.12

---

sentry/resource_sentry_project.go
sentry/resource_sentry_project_test.go

This fix tries to solve #54 .
Since the create endpoint of Sentry API only allows  the name for a new project, this change will update the resource to add the other properties.

Runs a project update right after it has been created

---

README.md
go.mod
go.sum
sentry/resource_sentry_project_rule.go

This updates go-sentry to the latest master commit [containing changes](https://github.com/jianyuan/go-sentry/pull/10) to support addition variable rules. It also changes the usage of `mapstructure.Decode` to  `mapstructure.WeakDecode` to allow for parameters to be optional, and avoid issues with type conversions coming from HCL.
There's also a quick fix for a bug preventing builds on master included due to the wrong type being used.
```terraform
resource "sentry_rule" "excessive_errors" {
name         = "Excessive Errors"
organization = "myorg"
project      = "myapp"
environment  = "production"
action_match = "all"
frequency    = 30
conditions = [
{
id       = "sentry.rules.conditions.event_frequency.EventFrequencyCondition"
value    = 500
interval = "1h"
}
]
actions = [
{
id        = …
```

Add additional variables to sentry_rule resource

---

sentry/provider.go

You can see how TFE provider does it [here](https://github.com/terraform-providers/terraform-provider-tfe/blob/master/tfe/provider.go#L58)

Make token not required so that env var can be used

---

sentry/helpers.go
sentry/resource_sentry_key.go
sentry/resource_sentry_organization.go
sentry/resource_sentry_project.go
sentry/resource_sentry_project_plugin.go
sentry/resource_sentry_project_rule.go
sentry/resource_sentry_team.go

This new helper properly and uniformly handles Sentry API 404 errors
with respect to the Terraform SDK. Prior to this commit, in most places
an API error was always interpretted as a missing resource. Now, a 404
is considered a missing resource and other API errors are surfaced as
real errors. This will ensure that, for example, a user with a malformed
API token (bad permissions, etc) doesn't wipe out Terraform state.
Fixes the following Github issues:
- https://github.com/jianyuan/terraform-provider-sentry/issues/40
- https://github.com/jianyuan/terraform-provider-sentry/issues/57

Introduce `checkClientGet` for 404 handling

---

sentry/helpers.go

In that case, there's no response and the checkClientGet method panics
It should print out the error instead
```
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd9e1e4][0m
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5:[0m
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5: goroutine 25 [running]:[0m
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5: github.com/jianyuan/terraform-provider-sentry/sentry.checkClientGet(...)[0m
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5: 	/home/jian/dev/terraform-provider-sentry/sentry/helpers.go:26[0m
2020-08-06T15:16:17.348Z debug plugin.terraform-provider-sentry_v0.5.5: …
```

Fix panic in case of unreachable sentry instance

---

sentry/resource_sentry_project.go

Hi @jianyuan, thank you for the useful plugin.
This PR enables to set `digests_min_delay` & `digests_max_delay` options for `sentry_project` resource. The source code of the plugin indicates that these options are already available, but since `Optional: true` was not specified in the Schema definition, the error `Computed attribute cannot be set` occurred. In this PR, I've defined a description in addition.

Enable to set digests_min_delay & digests_max_delay

---

.gitignore
sentry/provider.go
sentry/resource_sentry_default_key.go
sentry/resource_sentry_default_key_test.go
sentry/resource_sentry_project_rule.go

- Create a sentry_default_key resource to manage the key created together with a project, without going trough importing steps. Modeled after [resource_aws_default_subnet](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_default_subnet.go). This is especially helpful when creating a project with rate limits in place for DSN keys.
- sentry_default_key resource doesn't allow deletion to prevent unmanageable state drifts. 
- Also adds some checks for the float values in conditions/filters similar to actions in the rules.

add a default_key resource to manage the key created with a project

---

sentry/resource_sentry_key.go

Without this change if a user tries to create a Sentry key for a project
that doesn't exist then they get a not very useful error message from
`terraform apply`. For example, a Terraform resource that looks
something like this:
```
resource "sentry_key" "test" {
organization = "my-org"
project      = "project-that-does-not-exist"
name         = "test-sentry-fix"
}
```
will produce this when `terraform apply` runs:
```
Error: EOF
```
If you set `TF_LOG=trace` then you get more info but still nothing
particularly helpful:
```
apply errored, but we're indicating that via the Error pointer rather than returning it: EOF
```
This is because `resourceSentryKey` assumes that the project exists and
that a 404 from the Sentry API must indicate that the key doesn't exist
and should be created. …

Check to see if the project exists before creating keys

---

.github/workflows/test.yml
README.md
docs/index.md
sentry/provider.go
sentry/provider_test.go

Support sourcing Sentry auth token from the following environment variables:
1. `SENTRY_AUTH_TOKEN` ([Matches upstream](https://docs.sentry.io/product/cli/configuration/#to-authenticate-manually))
1. `SENTRY_TOKEN` (For backwards compatibility)
Addresses #104.

Support sourcing auth token from env var SENTRY_AUTH_TOKEN

---

sentry/config.go
sentry/data_source_sentry_key.go
sentry/data_source_sentry_organization.go
sentry/import_sentry_key.go
sentry/import_sentry_project_plugin.go
sentry/import_sentry_project_rule.go
sentry/import_sentry_team.go
sentry/provider.go
sentry/resource_sentry_default_key.go
sentry/resource_sentry_key.go
sentry/resource_sentry_organization.go
sentry/resource_sentry_project.go
sentry/resource_sentry_project_plugin.go
sentry/resource_sentry_project_rule.go
sentry/resource_sentry_team.go

Hello! The basic idea in this PR is to add more logging and to do so using the new [tflog](https://github.com/hashicorp/terraform-plugin-log)™️ library from Hashicorp. I also updated the [resource functions to their new context aware variant](https://www.terraform.io/plugin/sdkv2/guides/v2-upgrade-guide#more-support-for-context-context) which in a nutshell adds a `context.Context` object to many functions and demands a `diag.Diagnostics` object as part of the `return` of those functions. e.g.
```go
func providerContextConfigure(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
config := Config{
Token:   d.Get("token").(string),
BaseURL: d.Get("base_url").(string),
}
return config.Client(ctx)
}
```
I based my changes on these resources:
- …

Use tflog and new context aware functions

---

go.mod
go.sum

Hi @jianyuan, 
It seems the pagination fix found in  https://github.com/jianyuan/go-sentry/pull/20  is not included in this package. I upgraded `go-sentry`.

Upgrade to the latest go-sentry

---

go.mod
go.sum
sentry/config.go

Use `github.com/hashicorp/go-retryablehttp` as the default HTTP client.
If the response from Sentry was a rate limit error, wait until the reset time.

Retry requests when rate limited

---

docs/resources/organization_member.md
sentry/import_sentry_organization_member.go
sentry/resource_sentry_organization_member.go
sentry/resource_sentry_organization_member_test.go

Hello 👋 ,
I've created a `sentry_organization_member` resource. We've implemented this using my own fork at work and we're pretty happy with it. I wanted to share it with you as well.
Here's an example of how it works. Any feedback is appreciated 😄 
```hcl
resource "sentry_organization_member" "john_doe" {
email = "test@example.com"
role  = "member"
teams = ["my-team"]
}
```

Sentry Organization Member Resource

---

docs/resources/project.md
examples/resources/sentry_project/resource.tf
sentry/resource_sentry_project.go
sentry/resource_sentry_project_test.go

To introduce a new attribute to the `project` resource called `teams` which allows us to map many teams to a single project. Previously, we could only attached a single team to a project via the `team` attribute.
Due to Sentry's[ asynchronous handling](https://docs.sentry.io/api/teams/delete-a-team/) of team changes, these changes were found to be difficult to test via acceptance testing. Only a couple basic tests were added. For an extensive run through, please see this [video](https://www.canva.com/design/DAFGFB6OBpA/LjwlWUysSIYacHNkt1qcAg/watch?utm_content=DAFGFB6OBpA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton). (The API token in the video has been revoked since its recording :P)
```hcl
resource "sentry_team" "team1" {
organization = "tajpereira"
name         = …
```

Allow mapping many teams to one project (#33)

---

docs/data-sources/metric_alert.md
docs/index.md
docs/resources/metric_alert.md
examples/data-sources/sentry_metric_alert/data-source.tf
sentry/data_source_sentry_metric_alert.go
sentry/resource_sentry_metric_alert.go
sentry/resource_sentry_metric_alert_test.go

Piggyback off [GirtsZemitis](https://github.com/GirtsZemitis)'s great starter (https://github.com/jianyuan/terraform-provider-sentry/pull/196) to add an integration ID to metric alerts. 
We need to add an `integration_id` field to the metric alert action in order to specify the Slack Integration (in order to send alerts to Slack).
This is seen in the below example:
```tf
data "sentry_organization_integration" "slack" {
organization = "organization"
provider_key = "slack"
name         = "Organization" // corresponds to Slack's name of your organisation
}
resource "sentry_metric_alert" "main" {
// ...
trigger {
action {
type              = "slack"
target_type       = "specific"
target_identifier = "#slack-channel"
integration_id    = data.sentry_organization_integration.slack.id // <---- …
```

Add Integration ID to Metric Alert

---

sentry/platform_categories.go

When upgrading to a new version of the provider [v0.11.0](https://github.com/jianyuan/terraform-provider-sentry/releases/tag/v0.11.0), we found a problem that the configs does not pass verification, although everything works well on version 0.10.0
it seems that the problem is related to the [addition](https://github.com/jianyuan/terraform-provider-sentry/pull/241/) of project platform validation.
in our case, we use `python-aiohttp` and this type of platform is accepted by sentry when calling the API directly
```bash
> curl https://sentry.io/api/0/projects/.../ \
-H 'Authorization: Bearer ***' \
-X PUT \
-H 'Content-Type: application/json' \
-d '{"name":"...","platform":"python-aiohttp","slug":"..."}'
< HTTP/1.1 200 OK
```

fix: Add missing python-aiohttp

---

sentry/platform_categories.go

same problem as in this issue #255
we use the `apple` platform. unfortunately, it is not in the list of platforms, although the sentry API accepts this type
```bash
> curl https://sentry.io/api/0/projects/.../ \
-H 'Authorization: Bearer ***' \
-X PUT \
-H 'Content-Type: application/json' \
-d '{"name":"***","platform":"apple","slug":"***"}' \
< HTTP/1.1 200 OK
```

fix: Add missing apple to platformCategories

---

docs/resources/project.md
examples/resources/sentry_project/resource.tf
sentry/resource_sentry_project.go

This adds support for a `default_rules` input on the project resource and passes it through to the Create Project API - this leverages the change in https://github.com/jianyuan/go-sentry/pull/85.
Using the [`GetOkExists()`](https://pkg.go.dev/github.com/hashicorp/terraform/helper/schema#ResourceData.GetOkExists) method to see if `default_rules` input was set on the resource, so that if the input is not provided then the param is not set on the request and the existing behaviour is maintained.
I tested all 3 states locally by creating projects with different values - unset, set `true` and set `false` and observed the expected behaviour (alert created, alert created, alert not created), but unfortunately, I don't believe this can easily be tested the existing tests as there's no way get …

feat: Support for `deafult_rules` in project resource

---

docs/data-sources/metric_alert.md
docs/resources/metric_alert.md
examples/data-sources/sentry_metric_alert/data-source.tf
examples/resources/sentry_metric_alert/resource.tf
sentry/data_source_sentry_metric_alert.go
sentry/resource_sentry_metric_alert.go

This closes the #281 
I have managed to create and set the `input_channel_id` using this version of the provider.
Please let me know what you think @jianyuan - thanks in advance for your time 🙏

Feat | Add input_channel_id on sentry_metric_alert

---

sentry/resource_sentry_metric_alert.go

Fix an error when metric alert resource uses target identifier as integer. As TargetIdentifier type is `TypeString`, Int64 value cannot be used.
Related:
- go-sentry: https://github.com/jianyuan/go-sentry/commit/87a326682444a0cd8e5065f260bbb56616d363dc 
- terraform-sentry-provider: https://github.com/jianyuan/terraform-provider-sentry/commit/a67bdb8955f4ced4c6d6d0b6ab6b85e132129a56#diff-783f37843eff34fb8e005a86d573f55e3666e64fe73cdb6ff8673e8ba81554c1
https://github.com/jianyuan/terraform-provider-sentry/issues/185

fix: convert int64 to string for TypeString schema

---

internal/provider/data_source_issue_alert.go
internal/provider/data_source_issue_alert_test.go
internal/provider/resource_issue_alert.go
internal/sentrytypes/lossy_json_type.go
internal/sentrytypes/lossy_json_type_test.go
internal/sentrytypes/lossy_json_value.go
internal/sentrytypes/lossy_json_value_test.go

Work with Sentry API's inconsistent request/response formats and data types:
1. Sentry occasionally accepts a string but returns an integer, and sometimes does the opposite.
2. Sentry might return additional keys in an object beyond those provided.

feat: Custom lossy JSON type

---

internal/provider/resource_issue_alert.go
internal/provider/resource_issue_alert_test.go

Conditions are required, but can be set as empty array.
Previously if empty array would be set in tf config, null would be set in tf state after apply, which causes configuration missmatch.
Now if empty array set in tf config, empty array will be set in tf state.
Should fix https://github.com/jianyuan/terraform-provider-sentry/issues/366

fix: sentry_issue_alert.conditions empty array

---

internal/provider/resource_project_inbound_data_filter.go
internal/provider/resource_project_inbound_data_filter_test.go

The order of subfilters supplied in Terraform and the value returned by the API may not match. This is fixed by converting subfilters into a Terraform Set from a Terraform List.

fix: Convert sentry_project_inbound_data_filter.subfilters to set from list

---

docs/index.md
examples/provider/provider.tf
internal/provider/provider.go
sentry/provider.go

Revise the provider documentation to include instructions for changing data storage location

ref: update provider docs on changing data storage location

---

docs/index.md
examples/provider/provider.tf
examples/resources/sentry_issue_alert/resource.tf
internal/provider/provider.go
sentry/provider.go
templates/index.md.tmpl

Edit `sentry_issue_alert` documentation with an example on how to set a Slack note - Text to show alongside the notification

ref: update `sentry_issue_alert` Slack example with notes

---

go.mod
sentry/resource_sentry_metric_alert.go
sentry/resource_sentry_metric_alert_test.go

This closes https://github.com/jianyuan/terraform-provider-sentry/issues/406

feat: Adds support for `comparison_delta` to `sentry_metric_alert`

---

internal/provider/resource_team_member.go

This PR makes the `team_member` resource handle 404s more gracefully. Previously, 404s on organization members will block `terraform apply`. Now it doesn't.
Related to #446. This PR doesn't close that issue because there may be other places that requires similar changes.

Gracefully handle 404 in team member resource

---

internal/provider/resource_issue_alert.go
internal/provider/resource_issue_alert_test.go

The Sentry UI allows alert names of up to 256 characters:
However, the provider was limiting the name to 64 characters.
NOTE: I don't have a Sentry test environment, but I verified that this change builds, and did add a test with a longer name

Increase alert name limit to the real limit

---

docs/resources/project.md
examples/resources/sentry_project/resource.tf
internal/provider/resource_project.go
internal/provider/resource_project_test.go

This PR introduces the ability to configure custom filters for the project resource. The custom filters are blacklisted IPs, error messages, and releases.
Closes #455

Feat project filters

---

internal/provider/resource_project.go

Allow `other` as a platform option.

fix: Allow `other` as a platform option

---

docs/index.md
templates/index.md.tmpl

This PR adds a `NOTE` section in the Authentication section to inform about the user token that is required to have in order to manage Organization's members. This came out after receiving the response from the support to my question on managing organization's members.
- https://sentry.zendesk.com/hc/en-us/articles/27816731570331-How-can-I-change-the-scope-for-an-Organization-Auth-Token
- https://docs.sentry.io/api/auth/#auth-tokens

doc: add note section on the token for organization member management

---

GNUmakefile
docs/resources/project.md
internal/apiclient/api.yaml
internal/apiclient/apiclient.gen.go
internal/provider/resource_project.go
internal/provider/resource_project_test.go

New client security settings.
Closes #46, closes #461.

feat: Project resource supports client security settings

---

internal/sentryclient/rate_limiter.go

fix: Ensure resp is not nil before calling sentry.CheckResponse

---

internal/apiclient/api.yaml
internal/apiclient/apiclient.gen.go
internal/provider/resource_all_projects_spike_protection.go

- Do not terminate early when enumerating all related projects.
- Add RequiresReplace plan modifier to the `projects` attribute.

fix(resource/sentry_all_projects_spike_protection): Inconsistent result after apply

---

internal/apiclient/api.yaml
internal/apiclient/apiclient.gen.go
internal/provider/provider.go
internal/provider/provider_test.go

Validate the `base_url` and `token` upfront during provider setup. This ensures that configuration errors are caught as early as possible.

feat: Validate provider `base_url` and `token` upfront

---

docs/data-sources/key.md
internal/provider/data_source_client_key.go

Found this missing backtick that causes the inline code block to not properly display.

doc: add missing backtick in key datasource

---

docs/resources/dashboard.md
examples/resources/sentry_dashboard/resource.tf
sentry/resource_sentry_dashboard.go

The discover dataset is deprecated in favor of the `error-events` and `transaction-like` datasets, which better describes the data than using a `event.type:X` filters for the correct partitioning.
Is there a way to note down that `discover` was deprecated?
Contributes to https://github.com/getsentry/sentry-docs/issues/12618

fix(dashboard): Remove discover widget_type from examples

---

sentry/resource_sentry_organization_member.go

which is valid in Sentry no matter it's self-hosted or Saas.

feat: add admin role of org

---

docs/resources/project_ownership.md
internal/provider/resource_project_ownership.go

For some reason it was incorrectly documented. The options are all strings and can be one of:
* `Auto Assign to Issue Owner`
* `Auto Assign to Suspect Commits`
* `Turn off Auto-Assignment`
FYI @tazorax

Fix auto_assignment attribute documentation

---

internal/sentrydata/sentrydata.go
sentry/resource_sentry_organization_member.go

When using Integration token to invite member to a different role 
sample.tf
```
resource "sentry_organization_member" "sentry-organization-member" {
organization = org
email        = "username@domain.com"
role         = "manager"
}
```
we are getting generic error and it is not clear what is the cause of the error
> │ Error: unexpected status code: 400
but this PR changes the output message so that it is clear why it failing.
> Error: failed to create organization member, got status 400: ["Integration tokens are restricted to inviting new members with the member role only."]

fix error message
